env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=startx/sqlup
  - RELEASE=0.0.2
  - secure: Linv7Q1QtcUHHjfZs49UVFZW5lXE7+IwemzEEVU3f1QVH0XBs5fBh2e8wHp028JICpxX6fDugpG0KFq41c8s7DKLUce0fgnVHxfXB68fYh3d6t0co3kxIucyEU37iGT9iCmJjznHMZNITPnMLQex3bpUOitL+k62076tqWnD/RBtvmzBJrpU81d40RN1TSCk3tqGQV11Jh7wuZ/QjDttuTKl0aApc5xRKqRuxrb9ZuRWmB/JIPiwOWDBResV+aApnG8n1hhFSNt4Q+C09VZ0btsa6raqxC5Ws1og8z3bjnuKoZ1nbhLXjwDGYFW4mb4civdVlWcxt5xOOjZ3l/KbnW71mQhg69D2DV002J6VNR2OvnRnH0kOroWyYKdslB+osMb5FLP3O8VsE5K35t5IRvhSRlNxj1yyWyuHyGTcyWFJwn77KCDGysNV58yz2Pa7qp+hRe24PFgB9Q75K3RuODJ/Q4o30mwAVsA6BuzlG6lCXTsJ8VsAjfsgvQUQ2FwB1DlzM/sj9BelW04r3GWo6pwzI5QQ1/7p3MHXWfYf03o1WWvcxYG6zUkHdnFB0dnTrE17cw4dFV58oZSpMbUtvHDyDiuvSoQQwAq6Lxcr+KHfFSpR/rO3xjk5/I6aNMBJsAJ9yqJVFzde8RronAEG1N7h7pbi8NmCgcZHTKRBwZU= #DOCKER_USER
  - secure: cDZzS7EQg71iWb7AyDTVvtbZOzgfE6MteMnJsn0yt/UXFoEOUBrvXWfDzHFYxA+yFrfljfv50dS+sRyUdKyw41ixmN0MpjC6LYuF9ndUY/urBoZ6Ux7HByiwKm3/z71OKbsvgWJ0WWuJ8WB+TKmoDRUevdCVBAbQc3syjrLzGQ3q3NUJBSNPQQlIVgZAHg8mG82ir7Xu8Rai/ZK6ZL2jxew8EL58xjs5dEXL4+Nt7IYQlDQLFHfa3rnUgEMmUlMtT7ymkZQyXnVYr3EkPgQJjntuaSayFsCQ4X7b5ZghnRurZRM4sFVNy9e7+kECB4Iqlsc78w36R9wjR1El0kCKatB1j5fQ7rqZBkoW3IEWAetlvufbvsRrU9hraxubtpFshCph4VUwMSz2+s4n4Ub3h0J162PXWQoXCzdSzcUUmezLz6BFiqdhU4kATNykRVDncfqCDg469bfQAnQwE5DRr0blXxCP98BkcbSWTO+eG2FQXs/TsAmuYAOp1BEcrNEBYpu/0iJaYoRradS6u17cPySDrvpdnW4MG7A6vqVcTzFaIl4vagDjw7gScbadhNKnRurZ/9pKDcv9GJMPY8NG36kBYmm9FXWuevO6Do4PdsZ+rGBSEY2YMotSsnktlOoBdEw6zD2St1frRnbjSeTz2BNIq+YICPdKfEElYCYVLzg= #DOCKER_EMAIL
  - secure: K2Sq2WmGCL13K5pO+vpelB6zxd0U3JgTNpcbCirDN7DswG3ZnBOhxVGM19XO5ZrKd/yRgjhOavBUNCV1Sopa/5aMQvgEAGy95f/fh2LsPp3BfmrMUhHw3VezPxvGmcU3o+IGtdwI1ICVjkFDftxfrZb/uoz9WsJTnfspkJaXsMbzQitU0GOehoiFIcIz1+p9Am29yJchj+osNIu4HQ1xeSK7H4+gAs44mbBpoBNO6DQ5usWP7AR0JQneAeBognj7Ss4M7yhRbm/4FRJsWSc3hOkN2SGX02ieIQfU5tNnpGcjOu9oUeGlCUzYIXkA/XGttof0BpjpwU9tK0OxQ2UxKQY/TeKsHUPUxHan2m+VFmaMinLO9qtCwyk9YneLNjZajxnHC0x8Nz5hYlp1fLvUREqhcRa0w3ti13agFNRLOLDDstdOxcQ9uIsRoTq7h3zmu3TNNKi4g8HzQphDFDH12vzoUsrXgDJ/mxoa+sp8MYJCcjJCHB8KDtn9sd7iiX5vxkrUE+nWCveGsYdTBDwEsxTYDc6UDpFRE4aLWOINNEP8hSaaak3Vuz/Z6Dd4/dJLx7zj3u0YgRwcCeXH8u+vJbfQT5ebieaDGcUmlga4Ka9mKKJIgyq4QEPHXjjCO7ahyOLz4YvmhR25fTX9XrdsiDabO5RZFFjoO9DyFsq/oRw= #DOCKER_PASS

sudo: required

services:
- docker

before_install:
- 'echo "{ \"experimental\": true, \"storage-driver\": \"overlay2\", \"max-concurrent-downloads\":50,\"max-concurrent-uploads\": 50 }" | sudo tee /etc/docker/daemon.json'
- sudo service docker restart
- docker pull node:8-alpine
- docker images
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH"  == "test" ]; then echo "testing"; else echo $RELEASE ; fi`

script:
- docker build --squash -t $REPO:$TAG .
- docker run -d --name sxapi $REPO:$TAG npm test

after_success:
- docker push $REPO:$TAG
