env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=startx/sqlup
  - RELEASE=0.0.2
  - secure: mz+Tk0S+w/UWnTtdgqVK3tk1xp+aCONzR4PvoYgDH/7oP9r7xQKHVvX/V0rS9k83yhNjXyI5p7XnL6ovTRXpPkZIA+pThpVuwOpeyP8pdTwy8bSNHK2amVCimpBlrtjtJE1nWWc8gK9iINynTx5gi3DUGchm6EMhKFn2l91WFY8vxjK7I+fJ65+4QfNvMGHGSDml8HIFSO0qer9Rb2s7cpRt60YnFaiDfrbyXJ0D0G33W0fe2rgOQ7c39aK8UUDxjEpHaVrtghUGRt+GhEN/xL6ReJYIzURD3hNfrE++GDTPxzVY1jo8VQfyx6reGewL58ocdeENlFLuKttA7zSHQFRyp8dsQcY5723QNTYdRTdZzeMgN0elFJDHkEmlKzApvBIDsrWyDW4JtCpLk3ouxrx2ycwGEifp0P+ykjqwTlhRB6kC0SZM2nC+gIGW8qhninmBpxsb5dCc6gl3NwPRPqeFr6+EUKpqu4bzk3j87//IqXJ4BUssMD2SgyrYs3WsAer96rtgbXkGOQDIkudf3OY+vK+UhCtWLewKE4Hds7vR/OHhmGqITY0iWhGRXL70NDVM5w30qxA2cAhQfB/h9Z8yFNBXrK5kdYQZK9JP3zdLpRVFrz3X5NHE39iNSL8lrh1WkiYXt/ogDpowxEU2P05/er6M+Mb43poug51kgfg= #DOCKER_USER
  - secure: ii19JDQGFRGLTSV7sbAg3IyvHw6eU0FD5P0ixVVfAklbluZ/ohoVpVXZrJ4cC4TTbejn14za/RYBTmX3MMmwqv1Gndael8/VXDqIN3hN2unKQeNqeUTYV4rbMPugZG+7fc+flebgPXPv+xDpb+32/5qDbb84GWSbwljcCMjb4zIP3ng4ZPudK01wb6MbkRpu8aabA80N00CKpGPqKuTFrCQMao0P7fJfA+q8yUshoJPUBdkxrnv0JL/4OIRntJ2+gzxapqbhpP8EufSXgw68+Zgyq9/elDOzRx4l502Kw7PEGDvfio4tkHV5D2T4suyWAN61IP7Ye5eIN1aEIii4a9anhW1CfXkHsKh3LGaIZDUkZ7V9H36txgWOPEN3Qh20juhKNR4X3kBgnTvxOi2sBPtuBakTe/BgsN9EN+fQY4ZkVrIj2bmOLJKJQpz+HJZStdQwbn/5YPEYu+ksYvzomiYpoPSxb5ezMfAU6535/FW8KlEc28Fzbd/eSvuBzIbSxFb+iIzUc1xzCVG+z2txozwsORI9vphanfM/E2Zma9XXIPRi1+Rhle7G1vtXk9+IFkYTvF/77JpTRYRFRIiKZP5QPkw8VqTr4ef5vqXrBxb0sQpnt9I0gle83bgNFcfdNqD6VAiOIgM5EKj6OE7qJJ0wx+I8LHj0kR78ag8ZBw8= #DOCKER_PASS
sudo: required
services:
- docker

before_install:
- 'echo "{ \"experimental\": true, \"storage-driver\": \"overlay2\", \"max-concurrent-downloads\":50, \"max-concurrent-uploads\": 50 }" | sudo tee /etc/docker/daemon.json'
- sudo service docker restart
- docker pull node:8-alpine
- docker images
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH" == "test" ]; then echo "testing"; else echo $RELEASE ; fi`

script:
- docker build --squash -t $REPO:$TAG .
- docker run -d --name sxapi $REPO:$TAG

after_success:
- docker push $REPO:$TAG
