env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=startx/sqlup
  - RELEASE=0.0.2
  - secure: EI94CzYZR9C2Gq65sIvw1BNagukvKJoVh6zO6a9+6IN9LIheYwP16QfW79IuSMEoj5MVYKLDwbstz4lrygccUF3aBGKU9YRiinpazTwvKllE7RLjXWK6FTH82C9YPb2CyWgfrHH4SymczLinR781ps9k4p/iboYTG+N6JAi0i3OVPugMdn/1nT78BLOR7dQhEOMnZRN5SCPC9+B6hutE9/Q1armIR6RnFepHbUSDVrVCJAFc4kW7qkg4JM2iXw05fA1+dJQnlTsc7SIauaKyi7U7BHaBWqDbfNinfKkQGKr9JD73IKkMZQbtWHypXc49Cb3Gq5H0OKIdyVqjH3eY20WVL8uPgFORRAfjRkuPpf4VhE8BHM1A3/I62nRY8asQndveXG5G6dtnk7lTEJaLWrcm8N32Qn7B1Pko4sOFYQsvtNmp4MKmiUWI7NVxqIjVNMCd3IsJjKpl0tZL3iyv9YyblPZnuzGAeXzGBmRZGGKlv2yuIXw3iCsZmmq6vMJGRt4bslGU8iv7oCM86X8zzgMA6UUgHzH2oUr0hpHZ09WVGmCS51Fld+snrbRSXVpecgm69bCWCsaR8o7cLfhyKRA01FnXcKsL/ZRUbgiwfpKVSGEbcGEzoZrImDgtIk/sd37qGZz+ekBf7U5QO95GyiIjq5cayNo+YEBg6rf028M=
  - secure: LDKXEnwyUl9U4nMdvb9nYFPkpC+IwdHujYBWhSBuoWfUdfkYacRejPPXps4tFm1FzjPfF0H3f1qpudh9xpJb4HOGriPl8NDG18a10eIcz0zWRTKmb0imWVdDH3rQ/x5DOaWfRUXrlp5l+RNwAJ3IQnW85JVzV+lpaoPrwn5ppbEmu2MhV+4M75gyJdMNQogZiUYelK6x5x14bNByQ+d9Whuw+xeJIkqXy4PnvLpZnBkmjE20NkKnyEs+jnu+x1eG9ptejK9y78X8OK1DUhe//JZqWXHUH7OajkJPgplg6FETcQ2JWW6vckiPRlkpA/9H+XQKVqtyrTP2x1LwBHCMoIAPjoOP1BsFGAhMKwpqqdKt3nxQl0tkKiC3+Mv8UyqKcfIyZdj4XDAWwkUUqqEdstkHXoh3PVWqhUgS8V3HV73+Qa1Z6GSFwSyOfMPf//GCUq/cQvswqqWgFN6Vu66K1xi9oi+5Q1IqykVpjGjVUOP2lCZxyMYwZ6n9dKZue8uYSmj3gIAJMlVkQngsbGeTiNx6zyDaZEyF1vJYDGjH/X4xmm2IzPZP7+XI5dUvneS+cOLVBrWEDRn7Ictuf9TlpO8cDGfuMw27D6utqcdPPj2AShUPcXF5M4Db4aMXLcFhmCI9IDhc1LxncixyGBsY9ob2c5VD90uB21nUny5RmFQ=
sudo: required
services:
- docker
before_install:
- 'echo "{ \"experimental\": true, \"storage-driver\": \"overlay2\", \"max-concurrent-downloads\":50,
  \"max-concurrent-uploads\": 50 }" | sudo tee /etc/docker/daemon.json'
- sudo service docker restart
- docker pull node:8-alpine
- docker images
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH"
  == "test" ]; then echo "testing"; else echo $RELEASE ; fi`
script:
- docker build --squash -t $REPO:$TAG .
- docker run -d --name sxapi $REPO:$TAG
after_success:
- docker push $REPO:$TAG
