#!/bin/sh -e
#
# S2I assemble script for the 'sqlup' image.
# The 'assemble' script builds your application source ready to run.
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cat << "EOF"
|                _                 
|               (_ )               
|   ____   __ _  | |  _   _  ____  
|  / ___) / _` ) | | ( ) ( )(  _ \ 
|  \__  \( (_) | | | | (_) || (_) )
|  (____/ \___ |(___) \___/ | ___/ 
|            | |            | |    
|            (_)            (_)    
|    __  ____ ____ ____ _  _ ____ __   ____ 
|   / _\/ ___) ___|  __| \/ |  _ (  ) (  __)
|  /    \___ \___ \) _)/ \/ \) _ ( (_/\) _| 
|  \_/\_(____(____(____)_)(_(____|____(____) 
|  
|  
EOF

/bin/sx-nodejs build
exit 0;