#!/bin/sh -e
#
# S2I usage script
# The 'usage' script explay how to use the builder
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cat << "EOF"
|                _
|               (_ )
|   ____   __ _  | |  _   _  ____
|  / ___) / _` ) | | ( ) ( )(  _ \
|  \__  \( (_) | | | | (_) || (_) )
|  (____/ \___ |(___) \___/ | ___/
|            | |            | |
|            (_)            (_)
|   _  _  ____   __   ___ ____
|  / )( \/ ___) / _\ / __|  __)
|  ) \/ (\___ \/    ( (_ \) _)
|  \____/(____/\_/\_/\___(____)
|
|


/bin/sx-nodejs usageS2i
exit 0;