#!/bin/sh -e
#
# S2I assemble script for the 'sqlup' image.
# The 'assemble' script builds your application source ready to run.
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cat << "EOF"
|                _                 
|               (_ )               
|   ____   __ _  | |  _   _  ____  
|  / ___) / _` ) | | ( ) ( )(  _ \ 
|  \__  \( (_) | | | | (_) || (_) )
|  (____/ \___ |(___) \___/ | ___/ 
|            | |            | |    
|            (_)            (_)    
|    __  ____ ____ ____ _  _ ____ __   ____ 
|   / _\/ ___) ___|  __| \/ |  _ (  ) (  __)
|  /    \___ \___ \) _)/ \/ \) _ ( (_/\) _| 
|  \_/\_(____(____(____)_)(_(____|____(____) 
|  
|  
EOF
DIRFROM="$S2I_DEST"
if [[ -f /tmp/src/sqlup.json ]]; then
    echo "Found sqlup configuration in /tmp/src/sqlup.json"
    cp -f /tmp/src/sqlup.json $CONF_PATH/sqlup.json
    DIRFROM="/tmp/src"
    echo "Copy sqlup configuration to $CONF_PATH/sqlup.json"
fi;
if [[ -f /tmp/sqlup.json ]]; then
    echo "Found sqlup configuration in /tmp/sqlup.json"
    cp -f /tmp/sqlup.json $CONF_PATH/sqlup.json
    DIRFROM="/tmp"
    echo "Copy sqlup configuration to $CONF_PATH/sqlup.json"
fi;
if [[ -f $APP_PATH/sqlup.json ]]; then
    echo "Found sqlup configuration in $APP_PATH/sqlup.json"
    cp -f $APP_PATH/sqlup.json $CONF_PATH/sqlup.json
    DIRFROM="$APP_PATH"
    echo "Copy sqlup configuration to $CONF_PATH/sqlup.json"
fi;
if [[ -d $DIRFROM ]]; then
  echo "Copy SQL scripts into $DATA_PATH/"
  cp -f -R $DIRFROM/* $DATA_PATH/
fi;
cd $APP_PATH
npm install -production
npm dedupe
npm cache verify
npm cache clean --force
exit 0;