#!/bin/sh -e
#
# S2I usage script
# The 'usage' script explay how to use the builder
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cat << "EOF"
|                _                 
|               (_ )               
|   ____   __ _  | |  _   _  ____  
|  / ___) / _` ) | | ( ) ( )(  _ \ 
|  \__  \( (_) | | | | (_) || (_) )
|  (____/ \___ |(___) \___/ | ___/ 
|            | |            | |    
|            (_)            (_)    
|   _  _  ____   __   ___ ____ 
|  / )( \/ ___) / _\ / __|  __)
|  ) \/ (\___ \/    ( (_ \) _) 
|  \____/(____/\_/\_/\___(____)
|  
|  

SQLUP usage

Usage:
  docker run $SX_ID npm [command]

- General Commands:
  start            start nodejs main application
  version          give the version of the npm environement
  dev:env          give a list of environemnt variables
  test             start a test serie
  test:start       start a test serie and start job if test success

EOF
exit 0;