apiVersion: v1
kind: Template
metadata:
  name: sqlup-configmap-template
  annotations:
    description: Template for creating an SQLUP job with configuration stored in a configMap object
    iconClass: icon-mysql-database
    tags: sqlup,nodejs,startx,job,sql
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "sqlup"
  stringData:
    sqlup.json: "${SQLUP_CONF}"
    v0.0.0.sql: "SET names 'utf8';"
    v0.0.1.sql: "SET names 'utf8';"
- kind: Jobs
  apiVersion: apps/v1beta1
  metadata:
    name: "sqlup"
  spec:
    template:
      metadata:
        labels:
          name: "sqlup"
          app: sqlup
          type: job
        annotations:
          pod.alpha.kubernetes.io/initialized: 'true'
          scheduler.alpha.kubernetes.io/affinity: "{}"
      spec:
        containers:
        - name: sqlup
          env:
          - name: SX_DEBUG
            value: false
          - name: NODE_ENV
            value: development
          - name: SQLUP_HOST
            value: "${DB_HOST}"
          - name: SQLUP_PWD
            value: "${DB_PWD}"
          - name: SQLUP_DB
            value: "${DB_NAME}"
          image: "startx/sqlup:${IMAGE_NAME}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "${MEMORY_LIMIT}"
              cpu: 0.1
            limits:
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          - mountPath: "/sqlup"
            name: sqlup
        volumes:
          - name: sqlup
            configMap:
              name: "sqlup"
              items:
              - key: sqlup.json
                path: sqlup.json
              - key: v0.0.0.sql
                path: v0.0.0.sql
              - key: v0.0.1.sql
                path: v0.0.1.sql
parameters:
- name: IMAGE_NAME
  description: SQLUP release to use (available are latest, testing, stable or 0.0.8)
  value: latest
  required: true
- name: DB_HOST
  description: database service name or hostname to connect to
  value: mysql
  required: true
- name: DB_PWD
  description: database password to use
  value: mypassword
  required: true
- name: DB_NAME
  description: database name to use
  value: mydatabase
  required: true
- name: MEMORY_LIMIT
  displayName: Memory Limit for data nodes
  description: Maximum amount of memory data container can use.
  value: 128Mi
- name: SQLUP_CONF
  displayName: Configuration object (injected into the configMap)
  description: Json object string describing the application a see in https://github.com/startx/sqlup/blob/master/docs/guides/2.Configure.md
  value: >-
    {
        "name": "sqlup-dev",
        "version": "0.0.2",
        "path": "{{{DATA_PATH}}}",
        "waitStartup": 20,
        "server": {
            "type": "mysql",
            "host": "{{{SQLUP_HOST}}}",
            "port": "3306",
            "user": "root",
            "password": "{{{SQLUP_PWD}}}",
            "database": "{{{SQLUP_DB}}}"
        },
        "sequence": {
            "0.0.0": "v0.0.0.sql",
            "0.0.1": "v0.0.1.sql"
        }
    }
  required: true
labels:
  template: sqlup-configMap-template